/*
ParallelCluster

ParallelCluster API

API version: 3.10.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateComputeFleetRequestContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateComputeFleetRequestContent{}

// UpdateComputeFleetRequestContent struct for UpdateComputeFleetRequestContent
type UpdateComputeFleetRequestContent struct {
	Status RequestedComputeFleetStatus `json:"status"`
}

type _UpdateComputeFleetRequestContent UpdateComputeFleetRequestContent

// NewUpdateComputeFleetRequestContent instantiates a new UpdateComputeFleetRequestContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateComputeFleetRequestContent(status RequestedComputeFleetStatus) *UpdateComputeFleetRequestContent {
	this := UpdateComputeFleetRequestContent{}
	this.Status = status
	return &this
}

// NewUpdateComputeFleetRequestContentWithDefaults instantiates a new UpdateComputeFleetRequestContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateComputeFleetRequestContentWithDefaults() *UpdateComputeFleetRequestContent {
	this := UpdateComputeFleetRequestContent{}
	return &this
}

// GetStatus returns the Status field value
func (o *UpdateComputeFleetRequestContent) GetStatus() RequestedComputeFleetStatus {
	if o == nil {
		var ret RequestedComputeFleetStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *UpdateComputeFleetRequestContent) GetStatusOk() (*RequestedComputeFleetStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *UpdateComputeFleetRequestContent) SetStatus(v RequestedComputeFleetStatus) {
	o.Status = v
}

func (o UpdateComputeFleetRequestContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateComputeFleetRequestContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *UpdateComputeFleetRequestContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateComputeFleetRequestContent := _UpdateComputeFleetRequestContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateComputeFleetRequestContent)

	if err != nil {
		return err
	}

	*o = UpdateComputeFleetRequestContent(varUpdateComputeFleetRequestContent)

	return err
}

type NullableUpdateComputeFleetRequestContent struct {
	value *UpdateComputeFleetRequestContent
	isSet bool
}

func (v NullableUpdateComputeFleetRequestContent) Get() *UpdateComputeFleetRequestContent {
	return v.value
}

func (v *NullableUpdateComputeFleetRequestContent) Set(val *UpdateComputeFleetRequestContent) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateComputeFleetRequestContent) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateComputeFleetRequestContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateComputeFleetRequestContent(val *UpdateComputeFleetRequestContent) *NullableUpdateComputeFleetRequestContent {
	return &NullableUpdateComputeFleetRequestContent{value: val, isSet: true}
}

func (v NullableUpdateComputeFleetRequestContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateComputeFleetRequestContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
