/*
ParallelCluster

ParallelCluster API

API version: 3.11.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetClusterStackEventsResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetClusterStackEventsResponseContent{}

// GetClusterStackEventsResponseContent struct for GetClusterStackEventsResponseContent
type GetClusterStackEventsResponseContent struct {
	// Token to use for paginated requests.
	NextToken *string `json:"nextToken,omitempty"`
	Events []StackEvent `json:"events,omitempty"`
}

// NewGetClusterStackEventsResponseContent instantiates a new GetClusterStackEventsResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetClusterStackEventsResponseContent() *GetClusterStackEventsResponseContent {
	this := GetClusterStackEventsResponseContent{}
	return &this
}

// NewGetClusterStackEventsResponseContentWithDefaults instantiates a new GetClusterStackEventsResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetClusterStackEventsResponseContentWithDefaults() *GetClusterStackEventsResponseContent {
	this := GetClusterStackEventsResponseContent{}
	return &this
}

// GetNextToken returns the NextToken field value if set, zero value otherwise.
func (o *GetClusterStackEventsResponseContent) GetNextToken() string {
	if o == nil || IsNil(o.NextToken) {
		var ret string
		return ret
	}
	return *o.NextToken
}

// GetNextTokenOk returns a tuple with the NextToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetClusterStackEventsResponseContent) GetNextTokenOk() (*string, bool) {
	if o == nil || IsNil(o.NextToken) {
		return nil, false
	}
	return o.NextToken, true
}

// HasNextToken returns a boolean if a field has been set.
func (o *GetClusterStackEventsResponseContent) HasNextToken() bool {
	if o != nil && !IsNil(o.NextToken) {
		return true
	}

	return false
}

// SetNextToken gets a reference to the given string and assigns it to the NextToken field.
func (o *GetClusterStackEventsResponseContent) SetNextToken(v string) {
	o.NextToken = &v
}

// GetEvents returns the Events field value if set, zero value otherwise.
func (o *GetClusterStackEventsResponseContent) GetEvents() []StackEvent {
	if o == nil || IsNil(o.Events) {
		var ret []StackEvent
		return ret
	}
	return o.Events
}

// GetEventsOk returns a tuple with the Events field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetClusterStackEventsResponseContent) GetEventsOk() ([]StackEvent, bool) {
	if o == nil || IsNil(o.Events) {
		return nil, false
	}
	return o.Events, true
}

// HasEvents returns a boolean if a field has been set.
func (o *GetClusterStackEventsResponseContent) HasEvents() bool {
	if o != nil && !IsNil(o.Events) {
		return true
	}

	return false
}

// SetEvents gets a reference to the given []StackEvent and assigns it to the Events field.
func (o *GetClusterStackEventsResponseContent) SetEvents(v []StackEvent) {
	o.Events = v
}

func (o GetClusterStackEventsResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetClusterStackEventsResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NextToken) {
		toSerialize["nextToken"] = o.NextToken
	}
	if !IsNil(o.Events) {
		toSerialize["events"] = o.Events
	}
	return toSerialize, nil
}

type NullableGetClusterStackEventsResponseContent struct {
	value *GetClusterStackEventsResponseContent
	isSet bool
}

func (v NullableGetClusterStackEventsResponseContent) Get() *GetClusterStackEventsResponseContent {
	return v.value
}

func (v *NullableGetClusterStackEventsResponseContent) Set(val *GetClusterStackEventsResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableGetClusterStackEventsResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableGetClusterStackEventsResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetClusterStackEventsResponseContent(val *GetClusterStackEventsResponseContent) *NullableGetClusterStackEventsResponseContent {
	return &NullableGetClusterStackEventsResponseContent{value: val, isSet: true}
}

func (v NullableGetClusterStackEventsResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetClusterStackEventsResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


