/*
ParallelCluster

ParallelCluster API

API version: 3.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateClusterRequestContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateClusterRequestContent{}

// UpdateClusterRequestContent struct for UpdateClusterRequestContent
type UpdateClusterRequestContent struct {
	// Cluster configuration as a YAML document.
	ClusterConfiguration string `json:"clusterConfiguration"`
}

type _UpdateClusterRequestContent UpdateClusterRequestContent

// NewUpdateClusterRequestContent instantiates a new UpdateClusterRequestContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateClusterRequestContent(clusterConfiguration string) *UpdateClusterRequestContent {
	this := UpdateClusterRequestContent{}
	this.ClusterConfiguration = clusterConfiguration
	return &this
}

// NewUpdateClusterRequestContentWithDefaults instantiates a new UpdateClusterRequestContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateClusterRequestContentWithDefaults() *UpdateClusterRequestContent {
	this := UpdateClusterRequestContent{}
	return &this
}

// GetClusterConfiguration returns the ClusterConfiguration field value
func (o *UpdateClusterRequestContent) GetClusterConfiguration() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClusterConfiguration
}

// GetClusterConfigurationOk returns a tuple with the ClusterConfiguration field value
// and a boolean to check if the value has been set.
func (o *UpdateClusterRequestContent) GetClusterConfigurationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClusterConfiguration, true
}

// SetClusterConfiguration sets field value
func (o *UpdateClusterRequestContent) SetClusterConfiguration(v string) {
	o.ClusterConfiguration = v
}

func (o UpdateClusterRequestContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateClusterRequestContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["clusterConfiguration"] = o.ClusterConfiguration
	return toSerialize, nil
}

func (o *UpdateClusterRequestContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"clusterConfiguration",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateClusterRequestContent := _UpdateClusterRequestContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateClusterRequestContent)

	if err != nil {
		return err
	}

	*o = UpdateClusterRequestContent(varUpdateClusterRequestContent)

	return err
}

type NullableUpdateClusterRequestContent struct {
	value *UpdateClusterRequestContent
	isSet bool
}

func (v NullableUpdateClusterRequestContent) Get() *UpdateClusterRequestContent {
	return v.value
}

func (v *NullableUpdateClusterRequestContent) Set(val *UpdateClusterRequestContent) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateClusterRequestContent) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateClusterRequestContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateClusterRequestContent(val *UpdateClusterRequestContent) *NullableUpdateClusterRequestContent {
	return &NullableUpdateClusterRequestContent{value: val, isSet: true}
}

func (v NullableUpdateClusterRequestContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateClusterRequestContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


