/*
ParallelCluster

ParallelCluster API

API version: 3.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Change type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Change{}

// Change struct for Change
type Change struct {
	Parameter *string `json:"parameter,omitempty"`
	CurrentValue *string `json:"currentValue,omitempty"`
	RequestedValue *string `json:"requestedValue,omitempty"`
}

// NewChange instantiates a new Change object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChange() *Change {
	this := Change{}
	return &this
}

// NewChangeWithDefaults instantiates a new Change object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChangeWithDefaults() *Change {
	this := Change{}
	return &this
}

// GetParameter returns the Parameter field value if set, zero value otherwise.
func (o *Change) GetParameter() string {
	if o == nil || IsNil(o.Parameter) {
		var ret string
		return ret
	}
	return *o.Parameter
}

// GetParameterOk returns a tuple with the Parameter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Change) GetParameterOk() (*string, bool) {
	if o == nil || IsNil(o.Parameter) {
		return nil, false
	}
	return o.Parameter, true
}

// HasParameter returns a boolean if a field has been set.
func (o *Change) HasParameter() bool {
	if o != nil && !IsNil(o.Parameter) {
		return true
	}

	return false
}

// SetParameter gets a reference to the given string and assigns it to the Parameter field.
func (o *Change) SetParameter(v string) {
	o.Parameter = &v
}

// GetCurrentValue returns the CurrentValue field value if set, zero value otherwise.
func (o *Change) GetCurrentValue() string {
	if o == nil || IsNil(o.CurrentValue) {
		var ret string
		return ret
	}
	return *o.CurrentValue
}

// GetCurrentValueOk returns a tuple with the CurrentValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Change) GetCurrentValueOk() (*string, bool) {
	if o == nil || IsNil(o.CurrentValue) {
		return nil, false
	}
	return o.CurrentValue, true
}

// HasCurrentValue returns a boolean if a field has been set.
func (o *Change) HasCurrentValue() bool {
	if o != nil && !IsNil(o.CurrentValue) {
		return true
	}

	return false
}

// SetCurrentValue gets a reference to the given string and assigns it to the CurrentValue field.
func (o *Change) SetCurrentValue(v string) {
	o.CurrentValue = &v
}

// GetRequestedValue returns the RequestedValue field value if set, zero value otherwise.
func (o *Change) GetRequestedValue() string {
	if o == nil || IsNil(o.RequestedValue) {
		var ret string
		return ret
	}
	return *o.RequestedValue
}

// GetRequestedValueOk returns a tuple with the RequestedValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Change) GetRequestedValueOk() (*string, bool) {
	if o == nil || IsNil(o.RequestedValue) {
		return nil, false
	}
	return o.RequestedValue, true
}

// HasRequestedValue returns a boolean if a field has been set.
func (o *Change) HasRequestedValue() bool {
	if o != nil && !IsNil(o.RequestedValue) {
		return true
	}

	return false
}

// SetRequestedValue gets a reference to the given string and assigns it to the RequestedValue field.
func (o *Change) SetRequestedValue(v string) {
	o.RequestedValue = &v
}

func (o Change) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Change) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Parameter) {
		toSerialize["parameter"] = o.Parameter
	}
	if !IsNil(o.CurrentValue) {
		toSerialize["currentValue"] = o.CurrentValue
	}
	if !IsNil(o.RequestedValue) {
		toSerialize["requestedValue"] = o.RequestedValue
	}
	return toSerialize, nil
}

type NullableChange struct {
	value *Change
	isSet bool
}

func (v NullableChange) Get() *Change {
	return v.value
}

func (v *NullableChange) Set(val *Change) {
	v.value = val
	v.isSet = true
}

func (v NullableChange) IsSet() bool {
	return v.isSet
}

func (v *NullableChange) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChange(val *Change) *NullableChange {
	return &NullableChange{value: val, isSet: true}
}

func (v NullableChange) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChange) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


