/*
ParallelCluster

ParallelCluster API

API version: 3.11.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetImageLogEventsResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetImageLogEventsResponseContent{}

// GetImageLogEventsResponseContent struct for GetImageLogEventsResponseContent
type GetImageLogEventsResponseContent struct {
	// Token to use for paginated requests.
	NextToken *string `json:"nextToken,omitempty"`
	// Token to use for paginated requests.
	PrevToken *string `json:"prevToken,omitempty"`
	Events []LogEvent `json:"events,omitempty"`
}

// NewGetImageLogEventsResponseContent instantiates a new GetImageLogEventsResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetImageLogEventsResponseContent() *GetImageLogEventsResponseContent {
	this := GetImageLogEventsResponseContent{}
	return &this
}

// NewGetImageLogEventsResponseContentWithDefaults instantiates a new GetImageLogEventsResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetImageLogEventsResponseContentWithDefaults() *GetImageLogEventsResponseContent {
	this := GetImageLogEventsResponseContent{}
	return &this
}

// GetNextToken returns the NextToken field value if set, zero value otherwise.
func (o *GetImageLogEventsResponseContent) GetNextToken() string {
	if o == nil || IsNil(o.NextToken) {
		var ret string
		return ret
	}
	return *o.NextToken
}

// GetNextTokenOk returns a tuple with the NextToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetImageLogEventsResponseContent) GetNextTokenOk() (*string, bool) {
	if o == nil || IsNil(o.NextToken) {
		return nil, false
	}
	return o.NextToken, true
}

// HasNextToken returns a boolean if a field has been set.
func (o *GetImageLogEventsResponseContent) HasNextToken() bool {
	if o != nil && !IsNil(o.NextToken) {
		return true
	}

	return false
}

// SetNextToken gets a reference to the given string and assigns it to the NextToken field.
func (o *GetImageLogEventsResponseContent) SetNextToken(v string) {
	o.NextToken = &v
}

// GetPrevToken returns the PrevToken field value if set, zero value otherwise.
func (o *GetImageLogEventsResponseContent) GetPrevToken() string {
	if o == nil || IsNil(o.PrevToken) {
		var ret string
		return ret
	}
	return *o.PrevToken
}

// GetPrevTokenOk returns a tuple with the PrevToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetImageLogEventsResponseContent) GetPrevTokenOk() (*string, bool) {
	if o == nil || IsNil(o.PrevToken) {
		return nil, false
	}
	return o.PrevToken, true
}

// HasPrevToken returns a boolean if a field has been set.
func (o *GetImageLogEventsResponseContent) HasPrevToken() bool {
	if o != nil && !IsNil(o.PrevToken) {
		return true
	}

	return false
}

// SetPrevToken gets a reference to the given string and assigns it to the PrevToken field.
func (o *GetImageLogEventsResponseContent) SetPrevToken(v string) {
	o.PrevToken = &v
}

// GetEvents returns the Events field value if set, zero value otherwise.
func (o *GetImageLogEventsResponseContent) GetEvents() []LogEvent {
	if o == nil || IsNil(o.Events) {
		var ret []LogEvent
		return ret
	}
	return o.Events
}

// GetEventsOk returns a tuple with the Events field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetImageLogEventsResponseContent) GetEventsOk() ([]LogEvent, bool) {
	if o == nil || IsNil(o.Events) {
		return nil, false
	}
	return o.Events, true
}

// HasEvents returns a boolean if a field has been set.
func (o *GetImageLogEventsResponseContent) HasEvents() bool {
	if o != nil && !IsNil(o.Events) {
		return true
	}

	return false
}

// SetEvents gets a reference to the given []LogEvent and assigns it to the Events field.
func (o *GetImageLogEventsResponseContent) SetEvents(v []LogEvent) {
	o.Events = v
}

func (o GetImageLogEventsResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetImageLogEventsResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NextToken) {
		toSerialize["nextToken"] = o.NextToken
	}
	if !IsNil(o.PrevToken) {
		toSerialize["prevToken"] = o.PrevToken
	}
	if !IsNil(o.Events) {
		toSerialize["events"] = o.Events
	}
	return toSerialize, nil
}

type NullableGetImageLogEventsResponseContent struct {
	value *GetImageLogEventsResponseContent
	isSet bool
}

func (v NullableGetImageLogEventsResponseContent) Get() *GetImageLogEventsResponseContent {
	return v.value
}

func (v *NullableGetImageLogEventsResponseContent) Set(val *GetImageLogEventsResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableGetImageLogEventsResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableGetImageLogEventsResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetImageLogEventsResponseContent(val *GetImageLogEventsResponseContent) *NullableGetImageLogEventsResponseContent {
	return &NullableGetImageLogEventsResponseContent{value: val, isSet: true}
}

func (v NullableGetImageLogEventsResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetImageLogEventsResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


