/*
ParallelCluster

ParallelCluster API

API version: 3.10.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ConflictExceptionResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConflictExceptionResponseContent{}

// ConflictExceptionResponseContent This exception is thrown when a client request to create/modify content would result in a conflict.
type ConflictExceptionResponseContent struct {
	Message *string `json:"message,omitempty"`
}

// NewConflictExceptionResponseContent instantiates a new ConflictExceptionResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConflictExceptionResponseContent() *ConflictExceptionResponseContent {
	this := ConflictExceptionResponseContent{}
	return &this
}

// NewConflictExceptionResponseContentWithDefaults instantiates a new ConflictExceptionResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConflictExceptionResponseContentWithDefaults() *ConflictExceptionResponseContent {
	this := ConflictExceptionResponseContent{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ConflictExceptionResponseContent) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConflictExceptionResponseContent) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ConflictExceptionResponseContent) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ConflictExceptionResponseContent) SetMessage(v string) {
	o.Message = &v
}

func (o ConflictExceptionResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConflictExceptionResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableConflictExceptionResponseContent struct {
	value *ConflictExceptionResponseContent
	isSet bool
}

func (v NullableConflictExceptionResponseContent) Get() *ConflictExceptionResponseContent {
	return v.value
}

func (v *NullableConflictExceptionResponseContent) Set(val *ConflictExceptionResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableConflictExceptionResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableConflictExceptionResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConflictExceptionResponseContent(val *ConflictExceptionResponseContent) *NullableConflictExceptionResponseContent {
	return &NullableConflictExceptionResponseContent{value: val, isSet: true}
}

func (v NullableConflictExceptionResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConflictExceptionResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
