/*
ParallelCluster

ParallelCluster API

API version: 3.11.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the InternalServiceExceptionResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InternalServiceExceptionResponseContent{}

// InternalServiceExceptionResponseContent This exception is thrown on an unhandled service error.
type InternalServiceExceptionResponseContent struct {
	Message *string `json:"message,omitempty"`
}

// NewInternalServiceExceptionResponseContent instantiates a new InternalServiceExceptionResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInternalServiceExceptionResponseContent() *InternalServiceExceptionResponseContent {
	this := InternalServiceExceptionResponseContent{}
	return &this
}

// NewInternalServiceExceptionResponseContentWithDefaults instantiates a new InternalServiceExceptionResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInternalServiceExceptionResponseContentWithDefaults() *InternalServiceExceptionResponseContent {
	this := InternalServiceExceptionResponseContent{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *InternalServiceExceptionResponseContent) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalServiceExceptionResponseContent) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *InternalServiceExceptionResponseContent) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *InternalServiceExceptionResponseContent) SetMessage(v string) {
	o.Message = &v
}

func (o InternalServiceExceptionResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InternalServiceExceptionResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableInternalServiceExceptionResponseContent struct {
	value *InternalServiceExceptionResponseContent
	isSet bool
}

func (v NullableInternalServiceExceptionResponseContent) Get() *InternalServiceExceptionResponseContent {
	return v.value
}

func (v *NullableInternalServiceExceptionResponseContent) Set(val *InternalServiceExceptionResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableInternalServiceExceptionResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableInternalServiceExceptionResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInternalServiceExceptionResponseContent(val *InternalServiceExceptionResponseContent) *NullableInternalServiceExceptionResponseContent {
	return &NullableInternalServiceExceptionResponseContent{value: val, isSet: true}
}

func (v NullableInternalServiceExceptionResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInternalServiceExceptionResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


