/*
ParallelCluster

ParallelCluster API

API version: 3.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Scheduler type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Scheduler{}

// Scheduler struct for Scheduler
type Scheduler struct {
	Type string `json:"type"`
	Metadata *Metadata `json:"metadata,omitempty"`
}

type _Scheduler Scheduler

// NewScheduler instantiates a new Scheduler object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScheduler(type_ string) *Scheduler {
	this := Scheduler{}
	this.Type = type_
	return &this
}

// NewSchedulerWithDefaults instantiates a new Scheduler object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSchedulerWithDefaults() *Scheduler {
	this := Scheduler{}
	return &this
}

// GetType returns the Type field value
func (o *Scheduler) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Scheduler) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *Scheduler) SetType(v string) {
	o.Type = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *Scheduler) GetMetadata() Metadata {
	if o == nil || IsNil(o.Metadata) {
		var ret Metadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Scheduler) GetMetadataOk() (*Metadata, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *Scheduler) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given Metadata and assigns it to the Metadata field.
func (o *Scheduler) SetMetadata(v Metadata) {
	o.Metadata = &v
}

func (o Scheduler) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Scheduler) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *Scheduler) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varScheduler := _Scheduler{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varScheduler)

	if err != nil {
		return err
	}

	*o = Scheduler(varScheduler)

	return err
}

type NullableScheduler struct {
	value *Scheduler
	isSet bool
}

func (v NullableScheduler) Get() *Scheduler {
	return v.value
}

func (v *NullableScheduler) Set(val *Scheduler) {
	v.value = val
	v.isSet = true
}

func (v NullableScheduler) IsSet() bool {
	return v.isSet
}

func (v *NullableScheduler) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScheduler(val *Scheduler) *NullableScheduler {
	return &NullableScheduler{value: val, isSet: true}
}

func (v NullableScheduler) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScheduler) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


