/*
ParallelCluster

ParallelCluster API

API version: 3.11.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the BuildImageBadRequestExceptionResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BuildImageBadRequestExceptionResponseContent{}

// BuildImageBadRequestExceptionResponseContent This exception is thrown when a client calls the BuildImage API with an invalid request. This includes an error due to invalid image configuration.
type BuildImageBadRequestExceptionResponseContent struct {
	Message *string `json:"message,omitempty"`
	ConfigurationValidationErrors []ConfigValidationMessage `json:"configurationValidationErrors,omitempty"`
}

// NewBuildImageBadRequestExceptionResponseContent instantiates a new BuildImageBadRequestExceptionResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBuildImageBadRequestExceptionResponseContent() *BuildImageBadRequestExceptionResponseContent {
	this := BuildImageBadRequestExceptionResponseContent{}
	return &this
}

// NewBuildImageBadRequestExceptionResponseContentWithDefaults instantiates a new BuildImageBadRequestExceptionResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBuildImageBadRequestExceptionResponseContentWithDefaults() *BuildImageBadRequestExceptionResponseContent {
	this := BuildImageBadRequestExceptionResponseContent{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *BuildImageBadRequestExceptionResponseContent) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildImageBadRequestExceptionResponseContent) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *BuildImageBadRequestExceptionResponseContent) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *BuildImageBadRequestExceptionResponseContent) SetMessage(v string) {
	o.Message = &v
}

// GetConfigurationValidationErrors returns the ConfigurationValidationErrors field value if set, zero value otherwise.
func (o *BuildImageBadRequestExceptionResponseContent) GetConfigurationValidationErrors() []ConfigValidationMessage {
	if o == nil || IsNil(o.ConfigurationValidationErrors) {
		var ret []ConfigValidationMessage
		return ret
	}
	return o.ConfigurationValidationErrors
}

// GetConfigurationValidationErrorsOk returns a tuple with the ConfigurationValidationErrors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildImageBadRequestExceptionResponseContent) GetConfigurationValidationErrorsOk() ([]ConfigValidationMessage, bool) {
	if o == nil || IsNil(o.ConfigurationValidationErrors) {
		return nil, false
	}
	return o.ConfigurationValidationErrors, true
}

// HasConfigurationValidationErrors returns a boolean if a field has been set.
func (o *BuildImageBadRequestExceptionResponseContent) HasConfigurationValidationErrors() bool {
	if o != nil && !IsNil(o.ConfigurationValidationErrors) {
		return true
	}

	return false
}

// SetConfigurationValidationErrors gets a reference to the given []ConfigValidationMessage and assigns it to the ConfigurationValidationErrors field.
func (o *BuildImageBadRequestExceptionResponseContent) SetConfigurationValidationErrors(v []ConfigValidationMessage) {
	o.ConfigurationValidationErrors = v
}

func (o BuildImageBadRequestExceptionResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BuildImageBadRequestExceptionResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.ConfigurationValidationErrors) {
		toSerialize["configurationValidationErrors"] = o.ConfigurationValidationErrors
	}
	return toSerialize, nil
}

type NullableBuildImageBadRequestExceptionResponseContent struct {
	value *BuildImageBadRequestExceptionResponseContent
	isSet bool
}

func (v NullableBuildImageBadRequestExceptionResponseContent) Get() *BuildImageBadRequestExceptionResponseContent {
	return v.value
}

func (v *NullableBuildImageBadRequestExceptionResponseContent) Set(val *BuildImageBadRequestExceptionResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableBuildImageBadRequestExceptionResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableBuildImageBadRequestExceptionResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBuildImageBadRequestExceptionResponseContent(val *BuildImageBadRequestExceptionResponseContent) *NullableBuildImageBadRequestExceptionResponseContent {
	return &NullableBuildImageBadRequestExceptionResponseContent{value: val, isSet: true}
}

func (v NullableBuildImageBadRequestExceptionResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBuildImageBadRequestExceptionResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


