# Visit https://goreleaser.com for documentation on how to customize this
# behavior.
before:
  hooks:
    - go mod tidy
builds:
- env:
    # goreleaser does not work with CGO, it could also complicate
    # usage by users in CI/CD systems like Terraform Cloud where
    # they are unable to install libraries.
    - CGO_ENABLED=0
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - '-s -w -X main.version={{.Version}}'
  goos:
    # Suggested OS's to support:
    # https://developer.hashicorp.com/terraform/registry/providers/os-arch
    - freebsd
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - '386'
    - arm
    - arm64
  ignore:
    - goos: darwin
      goarch: '386'
  binary: 'terraform-provider-aws-parallelcluster_v{{ .Version }}'
archives:
- format: zip
  name_template: 'terraform-provider-aws-parallelcluster_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: 'terraform-provider-aws-parallelcluster_{{ .Version }}_manifest.json'
  # This file is expected by terraform registry
  name_template: 'terraform-provider-aws-parallelcluster_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
signs:
  - artifacts: checksum
    args:
      # if you are using this in a GitHub action or some other automated pipeline, you
      # need to pass the batch flag to indicate its not interactive.
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}" # set this environment variable for your signing key
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
release:
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: 'terraform-provider-aws-parallelcluster_{{ .Version }}_manifest.json'
  draft: true
changelog:
  disable: true
