AWSTemplateFormatVersion: 2010-09-09
Description: Infrastructure to make GitHub able to operate on the account.

Parameters:
  Organization:
    Description: Name of the GitHub organization that owns the repositories.
    Type: String
    Default: aws-tf
  ProviderRepository:
    Description: Name of the GitHub repository for the provider.
    Type: String
    Default: terraform-provider-aws-parallelcluster
  ModuleRepository:
    Description: Name of the GitHub repository for the module.
    Type: String
    Default: terraform-aws-parallelcluster

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: GitHub
        Parameters:
          - Organization
          - ProviderRepository
          - ModuleRepository

Resources:

  GithubOidc:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1

  ProviderE2ETestExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Role used by GitHub to run end-to-end tests for the provider.
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Ref GithubOidc
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
                token.actions.githubusercontent.com:sub: !Sub repo:${Organization}/${ProviderRepository}:ref:refs/heads/main
      ManagedPolicyArns:
        - !Ref E2ETestExecutionPolicy
      MaxSessionDuration: 7200

  ModuleE2ETestExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Role used by GitHub to run end-to-end tests for the module.
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Ref GithubOidc
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
                token.actions.githubusercontent.com:sub: !Sub repo:${Organization}/${ModuleRepository}:ref:refs/heads/main
      ManagedPolicyArns:
        - !Ref E2ETestExecutionPolicy
      MaxSessionDuration: 7200

  E2ETestExecutionPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Permissions to run end-to-end tests.
      ManagedPolicyName: E2ETestExecutionPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Resource: !Sub arn:aws:iam::${AWS::AccountId}:role/PCAPIUserRole-*
            Sid: AssumePCAPIUserRole
          - Effect: Allow
            Action:
              - ec2:DescribeVpcs
              - ec2:DescribeVpcAttribute
              - ec2:DescribeSubnets
              - ec2:DescribeSecurityGroups
              - ec2:AuthorizeSecurityGroupEgress
              - ec2:AuthorizeSecurityGroupIngress
              - ec2:RevokeSecurityGroupIngress
              - ec2:RevokeSecurityGroupEgress
              - ec2:DescribeSecurityGroupRules
            Resource: '*'
            Sid: EC2
          - Effect: Allow
            Action:
              - cloudformation:DescribeStacks
            Resource: !Sub arn:aws:cloudformation:*:${AWS::AccountId}:stack/*
            Sid: CloudFormation

Outputs:
  ProviderE2ETestExecutionRole:
    Value: !GetAtt ProviderE2ETestExecutionRole.Arn
  ModuleE2ETestExecutionRole:
    Value: !GetAtt ModuleE2ETestExecutionRole.Arn
