name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    strategy:
      fail-fast: false
      matrix:
        name:
          - Code Checks with Go 1.23.0
          - Code Checks with Go 1.24.1
        include:
          - name: Code Checks with Go 1.23.0
            go: 1.23.0
          - name: Code Checks with Go 1.24.1
            go: 1.24.1
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: false
      # See: https://github.com/golangci/golangci-lint
      # Configuration: https://golangci-lint.run/usage/configuration/
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.12.2
          args: --timeout=30m
