Region: us-east-1
Image:
 Os: alinux2
HeadNode:
 InstanceType: t3.small
 Networking:
   SubnetId: subnet-04771c60de343b20a
 Ssh:
   KeyName: pcluster20231113162056689300000001
Scheduling:
 Scheduler: slurm
 SlurmQueues:
   - Name: queue1
     CapacityType: ONDEMAND
     Networking:
       SubnetIds:
         - subnet-04771c60de343b20a
     ComputeResources:
       - Name: compute
         InstanceType: t3.small
         MinCount: 1
         MaxCount: 4
 SlurmSettings:
   QueueUpdateStrategy: TERMINATE
