Region: us-east-1
Image:
 Os: alinux2
HeadNode:
 InstanceType: t3.small
 Networking:
   SubnetId: subnet-02dc5b752a3b2891e
 Ssh:
   KeyName: pcluster20231106190513300500000001
Scheduling:
 Scheduler: slurm
 SlurmQueues:
   - Name: queue1
     CapacityType: ONDEMAND
     Networking:
       SubnetIds:
         - subnet-02dc5b752a3b2891e
       AssignPublicIp: true
     ComputeResources:
       - Name: compute
         InstanceType: t3.small
         MinCount: 1
         MaxCount: 3
 SlurmSettings:
   QueueUpdateStrategy: TERMINATE
